-- Email: verification, password reset, and the notifications the product sends.
--
-- Three things arrive here. Single-use tokens, because a reset link has to be
-- provable without a session and unusable twice. A record of the devices an
-- account signs in from, so a sign-in from a new one can be reported to its
-- owner. And a log of what was actually sent, which is the only way to answer
-- "did that email go out?" after the fact — a provider dashboard is not
-- something a self-hosted install has.

-- Verification is deliberately soft: nothing is gated on it, so an install with
-- no mail provider configured still works end to end. Existing accounts are
-- grandfathered rather than being asked to prove an address they have been
-- using for months.
ALTER TABLE users ADD COLUMN email_verified_at TIMESTAMPTZ;
UPDATE users SET email_verified_at = now() WHERE email IS NOT NULL;

-- The one notification that is a matter of taste rather than of security.
-- Everything else this server sends is about the account itself and is not
-- something to unsubscribe from.
ALTER TABLE users ADD COLUMN notify_weekly_review BOOLEAN NOT NULL DEFAULT TRUE;

/*
 * Tokens that stand in for a session.
 *
 * Only the hash is stored, for the same reason `auth_sessions` stores only a
 * hash: the raw value lives in a link in someone's inbox, and a database leak
 * should not hand over the ability to take over accounts. `used_at` rather than
 * a delete, so a second click on the same link can be told apart from a link
 * that never existed.
 */
CREATE TABLE auth_tokens (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose    TEXT NOT NULL CHECK (purpose IN ('password_reset', 'email_verification')),
  token_hash TEXT NOT NULL UNIQUE,
  -- The address the link was sent to. Verification proves *this* address, which
  -- is not necessarily the one on the row by the time the link is clicked.
  email      TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at    TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX auth_tokens_user ON auth_tokens (user_id, purpose);
CREATE INDEX auth_tokens_expiry ON auth_tokens (expires_at);

/*
 * Devices an account has signed in from.
 *
 * Separate from `auth_sessions` on purpose: a session is destroyed by signing
 * out and by expiry, and if "have I seen this device?" were answered from
 * sessions, signing out and back in would report itself as a new device every
 * time. This table is only ever added to.
 *
 * The fingerprint is the user agent alone, not the address. Home broadband,
 * mobile data and a train's wifi are the same person on the same laptop, and an
 * alert that fires on every network change is one people learn to ignore. The
 * address is recorded so the email can say where from, not to decide whether to
 * send it.
 */
CREATE TABLE known_devices (
  user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_hash   TEXT NOT NULL,
  user_agent    TEXT,
  last_ip       TEXT,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, device_hash)
);

/*
 * What was sent, and what happened to it.
 *
 * `user_id` survives the account it belonged to as NULL rather than cascading,
 * because the last email an account ever receives is the one confirming it was
 * deleted — and that record would otherwise delete itself a moment after being
 * written.
 *
 * `idempotency_key` is what stops a notification going out twice. The weekly
 * review is generated by an hourly tick that is deliberately re-entrant, so
 * "already emailed" has to be a fact in the database rather than a hope about
 * scheduling.
 */
CREATE TABLE email_deliveries (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID REFERENCES users(id) ON DELETE SET NULL,
  to_email        TEXT NOT NULL,
  template        TEXT NOT NULL,
  subject         TEXT NOT NULL,
  idempotency_key TEXT UNIQUE,
  -- 'pending' while in flight, then 'sent', 'failed', or 'logged' (no provider
  -- configured). A row left at 'pending' is a process that died mid-send.
  status          TEXT NOT NULL,
  -- The provider's own id, for cross-referencing in the Resend dashboard.
  provider_id     TEXT,
  error           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX email_deliveries_user ON email_deliveries (user_id, created_at DESC);
CREATE INDEX email_deliveries_recent ON email_deliveries (created_at DESC);
