import type { FastifyBaseLogger } from 'fastify';
import { query, queryOne } from '../db.ts';
import { env } from '../env.ts';
import type { EmailMessage } from './templates.ts';
import { EmailDeliveryError, type OutboundEmail, transport } from './transport.ts';

/**
 * Everything between "this happened" and "a message left the building".
 *
 * The one rule this module exists to enforce: **sending email must never be
 * able to fail the thing that caused it.** Nobody's signup should 500 because
 * Resend is having an afternoon, and nobody's account should survive a deletion
 * because the confirmation bounced. So `sendEmail` does not throw — it records
 * what happened and returns.
 *
 * The record is not bookkeeping for its own sake. A self-hosted install has no
 * provider dashboard to look at, and "did the reset email actually go out?" is
 * the first question asked when someone cannot get in. `email_deliveries`
 * answers it, and its unique key on `idempotency_key` is what stops the hourly
 * review tick sending Monday's email seven times.
 */

export type SendStatus = 'sent' | 'logged' | 'failed' | 'skipped';

export interface SendResult {
  status: SendStatus;
  /** The provider's message id, when there was a provider and it accepted. */
  id?: string | null;
  /** Why it was skipped, or how it failed. */
  reason?: string;
}

export interface SendOptions {
  to: string;
  /** Null only for mail to an account that no longer exists. */
  userId: string | null;
  message: EmailMessage;
  /**
   * Makes the send at-most-once for this key, forever. Only worth setting for
   * mail generated by a job that may run again over the same facts.
   */
  idempotencyKey?: string;
  /**
   * Sends to the address but does not write it down.
   *
   * For the one message that outlives its recipient's account. `deleteAccount`
   * erases that account's mail history, and the deletion receipt is written
   * *after* it — so without this the erasure would end by putting the address
   * straight back into the table it had just been cleared out of. The row still
   * records that a receipt went out, and when, which is all the delivery log is
   * for; it simply no longer records who to.
   */
  redactRecipient?: boolean;
  headers?: Record<string, string>;
  logger?: FastifyBaseLogger;
}

/**
 * What stands in for an address that must not be kept.
 *
 * A marker rather than an empty string, because `to_email` is NOT NULL and a
 * blank there reads as a bug. Anyone looking at the row should be able to tell
 * that the address is missing on purpose.
 */
export const ERASED_RECIPIENT = '[erased]';

export async function sendEmail(options: SendOptions): Promise<SendResult> {
  const { message, logger } = options;

  // Redirection happens before anything is recorded, so the log says where the
  // message actually went rather than where it was addressed.
  const to = env.email.redirectTo ?? options.to;
  const redirected = Boolean(env.email.redirectTo && env.email.redirectTo !== options.to);
  // The redirect prefix is the intended address, which for a redacted send is
  // the one thing that must not be written down — and the subject is recorded.
  const subject =
    redirected && !options.redactRecipient
      ? `[to: ${options.to}] ${message.subject}`
      : message.subject;

  /*
   * The address as the database and the log file are allowed to remember it.
   *
   * Only the outbound message gets the real one, and it is never held anywhere
   * this process controls: it goes to the transport and out.
   */
  const recorded = options.redactRecipient ? ERASED_RECIPIENT : to;

  const deliveryId = await claimDelivery({
    userId: options.userId,
    to: recorded,
    subject,
    template: message.template,
    idempotencyKey: options.idempotencyKey,
  });

  // Someone already has this key. Not an error — it is the guard working.
  if (deliveryId === null) {
    logger?.debug({ template: message.template, key: options.idempotencyKey }, 'email already sent');
    return { status: 'skipped', reason: 'already sent' };
  }

  const outbound: OutboundEmail = {
    to,
    subject,
    html: message.html,
    text: message.text,
    headers: options.headers,
    idempotencyKey: options.idempotencyKey,
  };

  try {
    const result = await transport(logger).send(outbound);
    await finishDelivery(deliveryId, result.status, result.id, null);
    logger?.info(
      { template: message.template, to: recorded, providerId: result.id },
      result.status === 'sent' ? 'email sent' : 'email logged',
    );
    return { status: result.status, id: result.id };
  } catch (error) {
    const reason =
      error instanceof EmailDeliveryError
        ? error.message
        : error instanceof Error
          ? error.message
          : String(error);
    await finishDelivery(deliveryId, 'failed', null, reason);
    // Logged at error level because there is nobody else to tell: the caller is
    // about to return success to a user who is expecting an email.
    logger?.error(
      { err: error, template: message.template, to: recorded },
      'email delivery failed',
    );
    return { status: 'failed', reason };
  }
}

/**
 * Reserves the right to send, and answers null if someone else already has it.
 *
 * The row goes in *before* the request rather than after, which is the whole
 * point: a crash between sending and recording would otherwise leave the key
 * unclaimed and let a retry send a duplicate. Recording an intent that never
 * completed is a stale 'pending' row; the other way round is a second email in
 * someone's inbox.
 */
async function claimDelivery(input: {
  userId: string | null;
  to: string;
  subject: string;
  template: string;
  idempotencyKey?: string;
}): Promise<string | null> {
  const row = await queryOne<{ id: string }>(
    `INSERT INTO email_deliveries (user_id, to_email, template, subject, idempotency_key, status)
     VALUES ($1,$2,$3,$4,$5,'pending')
     ON CONFLICT (idempotency_key) DO NOTHING
     RETURNING id`,
    [input.userId, input.to, input.template, input.subject, input.idempotencyKey ?? null],
  );
  return row?.id ?? null;
}

async function finishDelivery(
  id: string,
  status: SendStatus,
  providerId: string | null,
  error: string | null,
): Promise<void> {
  await query(
    'UPDATE email_deliveries SET status = $1, provider_id = $2, error = $3 WHERE id = $4',
    [status, providerId, error?.slice(0, 500) ?? null, id],
  );
}

/** What was sent to an account, newest first. Read by the admin panel. */
export async function recentDeliveries(
  userId: string,
  limit = 20,
): Promise<
  Array<{ template: string; subject: string; status: string; error: string | null; created_at: string }>
> {
  const rows = await query<any>(
    `SELECT template, subject, status, error, created_at
       FROM email_deliveries WHERE user_id = $1
   ORDER BY created_at DESC LIMIT $2`,
    [userId, limit],
  );
  return rows.map((row) => ({
    template: row.template,
    subject: row.subject,
    status: row.status,
    error: row.error,
    created_at: new Date(row.created_at).toISOString(),
  }));
}
