import type { FastifyBaseLogger } from 'fastify';
import { query, queryOne } from '../db.ts';
import { env } from '../env.ts';
import type { EmailMessage } from './templates.ts';
import { EmailDeliveryError, type OutboundEmail, transport } from './transport.ts';

/**
 * Everything between "this happened" and "a message left the building".
 *
 * The one rule this module exists to enforce: **sending email must never be
 * able to fail the thing that caused it.** Nobody's signup should 500 because
 * Resend is having an afternoon, and nobody's account should survive a deletion
 * because the confirmation bounced. So `sendEmail` does not throw — it records
 * what happened and returns.
 *
 * The record is not bookkeeping for its own sake. A self-hosted install has no
 * provider dashboard to look at, and "did the reset email actually go out?" is
 * the first question asked when someone cannot get in. `email_deliveries`
 * answers it, and its unique key on `idempotency_key` is what stops the hourly
 * review tick sending Monday's email seven times.
 *
 * That key used to stop rather more than that. A row is claimed *before* the
 * request, so a failed send left a claimed key behind and every later attempt
 * was answered "already sent" — which is the right answer for a duplicate and
 * exactly the wrong one for a message that never went. See
 * `MAX_DELIVERY_ATTEMPTS` and `claimDelivery`.
 */

export type SendStatus = 'sent' | 'logged' | 'failed' | 'skipped';

export interface SendResult {
  status: SendStatus;
  /** The provider's message id, when there was a provider and it accepted. */
  id?: string | null;
  /** Why it was skipped, or how it failed. */
  reason?: string;
}

export interface SendOptions {
  to: string;
  /** Null only for mail to an account that no longer exists. */
  userId: string | null;
  message: EmailMessage;
  /**
   * Makes the send at-most-once for this key, forever. Only worth setting for
   * mail generated by a job that may run again over the same facts.
   */
  idempotencyKey?: string;
  /**
   * Sends to the address but does not write it down.
   *
   * For the one message that outlives its recipient's account. `deleteAccount`
   * erases that account's mail history, and the deletion receipt is written
   * *after* it — so without this the erasure would end by putting the address
   * straight back into the table it had just been cleared out of. The row still
   * records that a receipt went out, and when, which is all the delivery log is
   * for; it simply no longer records who to.
   */
  redactRecipient?: boolean;
  headers?: Record<string, string>;
  /**
   * Marks this as one of many rather than one somebody is waiting for.
   *
   * The only thing it changes is queueing at the provider: a bulk send takes a
   * slot from the transport's rate limiter, an ordinary one goes straight out.
   * Set it on scheduled mail — the Monday review, the nudge — and never on
   * anything a person triggered, because the whole point is that a password
   * reset must not queue behind three thousand weekly reviews.
   */
  bulk?: boolean;
  logger?: FastifyBaseLogger;
}

/**
 * How many times one keyed message may be attempted, ever.
 *
 * A bound rather than a retry policy: the transport already retries a transient
 * failure inline, within the same send, so reaching a second attempt here means
 * the first one exhausted that. What this stops is the other failure — an
 * address that will never accept mail — becoming an hourly ritual for as long
 * as the sending pass keeps running.
 *
 * Five spans four hours of a Monday at the scheduler's hourly cadence, which is
 * a provider outage long enough to be somebody's problem rather than a blip.
 */
export const MAX_DELIVERY_ATTEMPTS = 5;

/**
 * How long a 'pending' row is believed before it is treated as abandoned.
 *
 * 'pending' means a claim was taken and nothing came back to settle it, which
 * in practice means the process died between the claim and the update. The
 * transport gives up on one request after fifteen seconds and retries at most
 * twice, so nothing honest is still in flight after a couple of minutes;
 * fifteen is far past that and nowhere near the hour before the next tick.
 */
const PENDING_ABANDONED_AFTER = '15 minutes';

/**
 * The rows a claim may be taken over, as one predicate in one place.
 *
 * Written once and used twice — by the claim itself and by `deliveryOutstanding`,
 * which exists to answer the same question cheaply without taking the claim. Two
 * spellings of "is this delivery still owed?" would be two things to keep in
 * step, and the day they drift is the day the scheduler either stops retrying
 * or never stops.
 */
const RECLAIMABLE = `
  d.attempts < ${MAX_DELIVERY_ATTEMPTS}
  AND (
        d.status = 'failed'
     OR (d.status = 'pending' AND d.last_attempt_at < now() - interval '${PENDING_ABANDONED_AFTER}')
  )`;

/**
 * What stands in for an address that must not be kept.
 *
 * A marker rather than an empty string, because `to_email` is NOT NULL and a
 * blank there reads as a bug. Anyone looking at the row should be able to tell
 * that the address is missing on purpose.
 */
export const ERASED_RECIPIENT = '[erased]';

export async function sendEmail(options: SendOptions): Promise<SendResult> {
  const { message, logger } = options;

  // Redirection happens before anything is recorded, so the log says where the
  // message actually went rather than where it was addressed.
  const to = env.email.redirectTo ?? options.to;
  const redirected = Boolean(env.email.redirectTo && env.email.redirectTo !== options.to);
  // The redirect prefix is the intended address, which for a redacted send is
  // the one thing that must not be written down — and the subject is recorded.
  const subject =
    redirected && !options.redactRecipient
      ? `[to: ${options.to}] ${message.subject}`
      : message.subject;

  /*
   * The address as the database and the log file are allowed to remember it.
   *
   * Only the outbound message gets the real one, and it is never held anywhere
   * this process controls: it goes to the transport and out.
   */
  const recorded = options.redactRecipient ? ERASED_RECIPIENT : to;

  const deliveryId = await claimDelivery({
    userId: options.userId,
    to: recorded,
    subject,
    template: message.template,
    idempotencyKey: options.idempotencyKey,
  });

  // Someone already has this key. Not an error — it is the guard working.
  if (deliveryId === null) {
    logger?.debug({ template: message.template, key: options.idempotencyKey }, 'email already sent');
    return { status: 'skipped', reason: 'already sent' };
  }

  const outbound: OutboundEmail = {
    to,
    subject,
    html: message.html,
    text: message.text,
    headers: options.headers,
    idempotencyKey: options.idempotencyKey,
    bulk: options.bulk,
  };

  try {
    const result = await transport(logger).send(outbound);
    await finishDelivery(deliveryId, result.status, result.id, null);
    logger?.info(
      { template: message.template, to: recorded, providerId: result.id },
      result.status === 'sent' ? 'email sent' : 'email logged',
    );
    return { status: result.status, id: result.id };
  } catch (error) {
    const reason =
      error instanceof EmailDeliveryError
        ? error.message
        : error instanceof Error
          ? error.message
          : String(error);
    await finishDelivery(deliveryId, 'failed', null, reason);
    // Logged at error level because there is nobody else to tell: the caller is
    // about to return success to a user who is expecting an email.
    logger?.error(
      { err: error, template: message.template, to: recorded },
      'email delivery failed',
    );
    return { status: 'failed', reason };
  }
}

/**
 * Reserves the right to send, and answers null if someone else already has it.
 *
 * The row goes in *before* the request rather than after, which is the whole
 * point: a crash between sending and recording would otherwise leave the key
 * unclaimed and let a retry send a duplicate. Recording an intent that never
 * completed is a stale 'pending' row; the other way round is a second email in
 * someone's inbox.
 *
 * The conflict is where the interesting half is. `DO NOTHING` treated every
 * existing row as proof the message had gone out, which is true of a 'sent' row
 * and false of the two states that mean the opposite — a send the provider
 * refused, and a claim whose process died before it could settle. Both are
 * re-granted here, bounded by `attempts`, and re-granting is *all* it is: the
 * update refuses to touch a row that is already 'sent', so the guard against
 * duplicates is exactly as strong as it was.
 *
 * One statement rather than a read followed by a write, for the reason the
 * whole table exists: two scheduler passes — or two replicas — asking at the
 * same instant must not both come away holding the same claim.
 */
async function claimDelivery(input: {
  userId: string | null;
  to: string;
  subject: string;
  template: string;
  idempotencyKey?: string;
}): Promise<string | null> {
  const row = await queryOne<{ id: string }>(
    `INSERT INTO email_deliveries AS d
            (user_id, to_email, template, subject, idempotency_key, status)
     VALUES ($1,$2,$3,$4,$5,'pending')
     ON CONFLICT (idempotency_key) DO UPDATE
            SET status = 'pending',
                attempts = d.attempts + 1,
                last_attempt_at = now(),
                -- Cleared rather than kept: the row now describes an attempt in
                -- flight, and last time's error read as this time's.
                error = NULL,
                provider_id = NULL
          WHERE ${RECLAIMABLE}
     RETURNING d.id`,
    [input.userId, input.to, input.template, input.subject, input.idempotencyKey ?? null],
  );
  return row?.id ?? null;
}

/**
 * Whether this keyed message was attempted, did not go, and has tries left —
 * without taking the claim.
 *
 * For the caller that has to decide whether re-deriving a message is worth it
 * at all. The scheduler is the one that does: on every tick of a Monday it
 * holds a review that is already written, and the only remaining question is
 * whether the mail announcing it ever left. Asking `sendEmail` would answer
 * that too, but only after re-reading the recipient, re-signing an unsubscribe
 * link and re-rendering the template — for what, at three in the afternoon, is
 * almost always "nothing to do". This is one indexed lookup instead.
 *
 * **A key nothing has ever claimed is false, not true**, and the distinction is
 * the whole reason this is not simply "is it unsent?". A missing row means no
 * attempt was ever made, which for the scheduler is not a failure to recover
 * from — it is a review that was generated by somebody pressing the button in
 * the app, where `POST /reviews/run` deliberately sends no mail because they
 * are already looking at it. Answering true here would post it to them on the
 * following Monday as though it were news.
 *
 * So this is narrowly "retry what broke", never "send what was never sent". The
 * gap that leaves is a send that threw *before* claiming its row, which is a
 * local failure — reading the recipient, rendering the template — in a pass
 * that is having much larger problems than one email.
 */
export async function deliveryNeedsRetry(idempotencyKey: string): Promise<boolean> {
  const row = await queryOne<{ owed: boolean }>(
    `SELECT ${RECLAIMABLE} AS owed FROM email_deliveries d WHERE d.idempotency_key = $1`,
    [idempotencyKey],
  );
  return row?.owed ?? false;
}

async function finishDelivery(
  id: string,
  status: SendStatus,
  providerId: string | null,
  error: string | null,
): Promise<void> {
  await query(
    'UPDATE email_deliveries SET status = $1, provider_id = $2, error = $3 WHERE id = $4',
    [status, providerId, error?.slice(0, 500) ?? null, id],
  );
}

/** What was sent to an account, newest first. Read by the admin panel. */
export async function recentDeliveries(
  userId: string,
  limit = 20,
): Promise<
  Array<{
    template: string;
    subject: string;
    status: string;
    error: string | null;
    attempts: number;
    created_at: string;
  }>
> {
  const rows = await query<any>(
    `SELECT template, subject, status, error, attempts, created_at
       FROM email_deliveries WHERE user_id = $1
   ORDER BY created_at DESC LIMIT $2`,
    [userId, limit],
  );
  return rows.map((row) => ({
    template: row.template,
    subject: row.subject,
    status: row.status,
    error: row.error,
    // Worth surfacing next to the status: 'sent' after four tries and 'sent'
    // first time are the same outcome and very different news.
    attempts: row.attempts,
    created_at: new Date(row.created_at).toISOString(),
  }));
}
