#!/usr/bin/env tsx
// Nine post templates, and one post built from each.
//
//   npx tsx scripts/content/post.mts                  # all nine, 1080x1350
//   npx tsx scripts/content/post.mts --only statement
//   npx tsx scripts/content/post.mts --size story
//
// A template is a layout; a POSTS entry is the copy poured into one. To ship a
// new post, add an entry — the layouts are meant to be reused, not rewritten.
// The nine were picked off a layout board so they fail differently from each
// other: three carry no character at all, three keep it subordinate to type or
// data, three let it lead. A feed of nine variations on one shape reads as one
// post; this is the spread that stops it.
//
// Where each layer comes from:
//
//   cast   packages/shared/src/cast.ts — the same geometry the phone, the
//          widget and the site draw, at any size, in any of eighteen moods.
//          Never redrawn by hand, never regenerated by a model.
//   type   apps/mobile/assets/fonts — Baloo2 for the shouting, Nunito for
//          reading, IBM Plex Mono for timestamps and labels. All three SIL OFL.
//   ground a CSS field by default. Pass `ground` on an entry to lay a
//          ComfyUI render from content/gen/ underneath instead (§10) — texture
//          only, never a subject, and never anything a number could sit on.
//
// Composition rules the layouts encode, learned by getting them wrong first:
// a lineup is not a composition; a mood needs its scene (`stir` draws the ladle
// and not the pot); one face at one weight is the amateur tell; and a figure
// without a halo and a real contact shadow floats on the ground like a sticker.
//
// Rasterised by headless Chrome: the only renderer here that reads both SVG and
// a webfont (sharp is not installed, ffmpeg does neither).

import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { figureMarkup, GRID, type CastName, type Mood, type Prop } from '../../packages/shared/src/cast'

/* ── frame ──────────────────────────────────────────────────────────── */

const SIZES: Record<string, { w: number; h: number }> = {
  post: { w: 1080, h: 1350 },
  story: { w: 1080, h: 1920 },
  square: { w: 1080, h: 1080 },
}

const FLAGS = new Set(['size', 'out', 'only'])
const argv = process.argv.slice(2)
const opts: Record<string, string> = {}
for (let i = 0; i < argv.length; i++) {
  const a = argv[i]
  if (!a.startsWith('--')) continue
  const name = a.slice(2)
  if (!FLAGS.has(name)) {
    console.error(`Unknown flag --${name}. Known: ${[...FLAGS].join(', ')}`)
    process.exit(1)
  }
  opts[name] = argv[++i]
}

const SIZE = opts.size ?? 'post'
const OUTDIR = opts.out ?? 'content/out/posts'
if (!SIZES[SIZE]) {
  console.error(`Unknown --size ${SIZE}. Known: ${Object.keys(SIZES).join(', ')}`)
  process.exit(1)
}
const { w: W, h: H } = SIZES[SIZE]

/**
 * The composition is laid out in a stage, which is the frame everywhere except
 * story. A 9:16 story is mostly chrome — the top and bottom ~250px sit under
 * Instagram's own UI — so there the stage stays the 4:5 composition, centred,
 * while the ground fills the whole frame. That puts every element inside the
 * safe area by construction instead of by a table of insets, and it means one
 * set of coordinates renders all three sizes.
 */
const STAGE_H = SIZE === 'story' ? 1350 : H
const STAGE_TOP = Math.round((H - STAGE_H) / 2)

/**
 * A figure's box, as a share of the stage height but capped against the frame
 * width. Without the cap a tall frame grows the figure until it runs out of
 * the sides; without the height share a square frame keeps a figure sized for
 * a taller one and swallows the type.
 */
const figBox = (hFrac: number, wFrac: number) => Math.round(Math.min(STAGE_H * hFrac, W * wFrac))

const FONTS = {
  display: 'apps/mobile/assets/fonts/Baloo2_800ExtraBold.ttf',
  text400: 'apps/mobile/assets/fonts/Nunito_400.woff2',
  text600: 'apps/mobile/assets/fonts/Nunito_600.woff2',
  text700: 'apps/mobile/assets/fonts/Nunito_700.woff2',
  mono400: 'apps/mobile/assets/fonts/PlexMono_400.woff2',
  mono500: 'apps/mobile/assets/fonts/PlexMono_500.woff2',
}

// Sampled from store/feature-graphic.png, as scripts/content/cards.mjs does.
const INK = '#1b1a15'
const CREAM = '#f7efe6'
const JADE = '#0f9a5a'

/** Each figure's mid ramp stop, for the halo it stands in (cast.ts FIGURES). */
const HALO: Record<CastName, string> = { ember: '#ffa51f', skye: '#3b9eff', plum: '#b06bff' }

/* ── the posts ──────────────────────────────────────────────────────── */

interface Base {
  key: string
  /** Optional ComfyUI render from content/gen/ laid under the CSS field. */
  ground?: string
}
type Post = Base &
  (
    | { template: 'statement'; kicker: string; headline: string }
    | { template: 'typed-day'; day: string; entries: { t: string; m: string }[]; foot: string }
    | { template: 'macro-bar'; headline: string; rows: { k: string; p: number; c: number; f: number }[] }
    | { template: 'glyph'; head: string; tail: string; name: CastName; mood: Mood }
    | { template: 'pair'; headline: string; cells: { name: CastName; mood: Mood; prop?: Prop; val: string; lbl: string }[] }
    | { template: 'carousel'; num: string; headline: string; name: CastName; mood: Mood }
    | { template: 'crop'; headline: string; name: CastName; mood: Mood; prop?: Prop }
    | { template: 'split'; headline: string; name: CastName; mood: Mood; prop?: Prop }
    | { template: 'staged'; headline: string; sub: string; name: CastName; mood: Mood }
  )

// One post per template. Every line is an idea about eating that stands on its
// own: none names a feature, shows a screen, or puts a number on an image.
const POSTS: Post[] = [
  {
    key: '01-statement',
    template: 'statement',
    kicker: 'No app required',
    headline: 'Eat first.<br>Log after.',
  },
  {
    key: '02-typed-day',
    template: 'typed-day',
    day: 'Tuesday',
    entries: [
      { t: '08:10', m: 'Toast, two eggs, black coffee' },
      { t: '13:30', m: 'Leftover rice and whatever was in the fridge' },
      { t: '17:45', m: 'Most of a bar of dark chocolate, standing up' },
      { t: '21:20', m: 'Beer sausages and a lager' },
    ],
    foot: 'A day is four sentences.',
  },
  {
    key: '03-macro-bar',
    template: 'macro-bar',
    headline: 'Same calories. Different day.',
    // Widths in canvas px. Each row totals the same, which is the whole point.
    rows: [
      { k: 'Mon', p: 120, c: 360, f: 150 },
      { k: 'Tue', p: 330, c: 150, f: 150 },
    ],
  },
  {
    key: '04-glyph',
    template: 'glyph',
    head: 'Dinner was',
    tail: 'fine',
    name: 'plum',
    mood: 'idle',
  },
  {
    key: '05-pair',
    template: 'pair',
    headline: 'Two plates. One number. Nothing alike.',
    cells: [
      { name: 'ember', mood: 'proud', val: 'Chicken &amp; rice', lbl: 'protein led' },
      { name: 'plum', mood: 'hold', prop: 'mug', val: 'Pastry &amp; latte', lbl: 'fat led' },
    ],
  },
  {
    key: '06-carousel',
    template: 'carousel',
    num: '01 / 05',
    headline: 'Three things nobody says about logging food',
    name: 'skye',
    mood: 'thinking',
  },
  {
    key: '07-crop',
    template: 'crop',
    headline: 'Nobody weighs the toast',
    name: 'ember',
    mood: 'hold',
    prop: 'toast',
  },
  {
    key: '08-split',
    template: 'split',
    headline: 'You already know what went in the bowl',
    name: 'skye',
    mood: 'hold',
    prop: 'bowl',
  },
  {
    key: '09-staged',
    template: 'staged',
    headline: 'A 1am snack belongs to yesterday',
    sub: 'Your day ends when you sleep, not at midnight.',
    name: 'plum',
    mood: 'sleepy',
    ground: 'content/gen/dsf3_grad_night_00001_.png',
  },
]

/* ── helpers ────────────────────────────────────────────────────────── */

const url = (p: string) => pathToFileURL(resolve(p)).href

/** One figure as a standalone SVG. `prefix` keeps gradient ids apart. */
function fig(name: CastName, mood: Mood, prefix: string, prop?: Prop): string {
  const f = figureMarkup(name, mood, prefix, prop)
  return `<svg viewBox="0 0 ${GRID} ${GRID}" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs>${f.defs}</defs>${f.shapes}</svg>`
}

/**
 * The signature: the real app icon, never the product name typed out and never
 * a coloured square standing in for it. store/icon-512.png is the jade ring
 * with the three macro dots inside — the drawing the cast came out of
 * (CAST.md), so the mark and the characters are visibly one family. Its ground
 * is cream rather than transparent, so it is set as a rounded tile and reads as
 * the app icon on a light field or a dark one.
 */
const ICON = 'store/icon-512.png'
function mark(pos: string, colour: string): string {
  return `<div class="mark" style="${pos};color:${colour}"><img src="${url(ICON)}" alt=""><span>Day So Far</span></div>`
}

/**
 * A halo in the figure's own colour and a blurred contact shadow, so it stands
 * on the ground instead of floating above it. `size` is the figure's box.
 */
function grounding(name: CastName, left: number, bottom: number, size: number, dark: boolean): string {
  const halo = `left:${Math.round(left - size * 0.14)}px;bottom:${Math.round(bottom - size * 0.1)}px;width:${Math.round(size * 1.28)}px;height:${Math.round(size * 1.28)}px;background:radial-gradient(circle at 50% 50%,${HALO[name]}${dark ? '3d' : '2b'} 0%,transparent 62%)`
  const shade = `left:${Math.round(left + size * 0.19)}px;bottom:${Math.round(bottom + size * 0.055)}px;width:${Math.round(size * 0.62)}px;height:${Math.round(size * 0.1)}px;background:${dark ? 'rgba(0,0,0,.42)' : 'rgba(27,26,21,.16)'};filter:blur(${Math.round(size * 0.035)}px)`
  return `<span class="halo" style="${halo}"></span><span class="shade" style="${shade}"></span>`
}

/** A grounded figure: its halo, its contact shadow and the drawing, placed. */
function figure(
  name: CastName,
  mood: Mood,
  prefix: string,
  size: number,
  left: number,
  /** How far past the stage's foot it sinks, as a share of its own box. */
  sink: number,
  dark: boolean,
  prop?: Prop,
): string {
  const bottom = Math.round(-size * sink)
  return (
    grounding(name, left, bottom, size, dark) +
    `<span class="fig" style="left:${left}px;bottom:${bottom}px;width:${size}px;height:${size}px">${fig(name, mood, prefix, prop)}</span>`
  )
}

const FIELDS: Record<string, string> = {
  warm: 'linear-gradient(152deg,#f7e0bd 0%,#efe6d2 38%,#dfeadb 72%,#cfe7d8 100%)',
  night: 'linear-gradient(158deg,#221d3a 0%,#2c2a4d 45%,#3b3a5e 100%)',
  amber: 'linear-gradient(150deg,#ffc266 0%,#f09733 100%)',
  ink: '#1b1a15',
  paper: '#fdf8f0',
}

/* ── templates ──────────────────────────────────────────────────────── */

/** Each returns the field it sits on and the markup that goes over it. */
function render(p: Post): { field: string; body: string } {
  switch (p.template) {
    case 'statement':
      return {
        field: FIELDS.amber,
        body:
          `<div class="pad c">` +
          `<div class="kicker">${p.kicker}</div>` +
          `<h1 class="d" style="font-size:130px;line-height:.96;color:#fffdf9">${p.headline}</h1>` +
          `</div>` +
          mark('bottom:76px;left:97px', 'rgba(255,255,255,.78)'),
      }

    case 'typed-day':
      return {
        field: FIELDS.paper,
        body:
          `<div class="pad col">` +
          `<div class="m500" style="font-size:29px;letter-spacing:.12em;text-transform:uppercase;color:#a89f92;margin-bottom:54px">${p.day}</div>` +
          `<ul class="list">` +
          p.entries
            .map(
              (e) =>
                `<li><span class="m400" style="font-size:31px;color:#b3a998;flex:none;width:119px">${e.t}</span>` +
                `<span class="t" style="font-size:44px;font-weight:600;color:${INK};line-height:1.25">${e.m}</span></li>`,
            )
            .join('') +
          `</ul>` +
          `<div class="t" style="margin-top:auto;font-size:38px;font-weight:700;color:${JADE}">${p.foot}</div>` +
          `</div>` +
          mark('bottom:76px;right:97px', 'rgba(27,26,21,.45)'),
      }

    case 'macro-bar':
      return {
        field: FIELDS.ink,
        body:
          `<div class="pad col" style="justify-content:space-between;padding:86px">` +
          `<h1 class="d" style="font-size:89px;line-height:1.02;color:${CREAM};max-width:13ch">${p.headline}</h1>` +
          `<div class="bars">` +
          p.rows
            .map(
              (r) =>
                `<div class="row">` +
                `<span class="m500" style="font-size:28px;letter-spacing:.1em;text-transform:uppercase;color:rgba(247,239,230,.55);width:110px;flex:none">${r.k}</span>` +
                `<span class="bar" style="background:#ffa51f;width:${r.p}px"></span>` +
                `<span class="bar" style="background:#3b9eff;width:${r.c}px"></span>` +
                `<span class="bar" style="background:#b06bff;width:${r.f}px"></span>` +
                `</div>`,
            )
            .join('') +
          `</div>` +
          `<div class="mark" style="position:static;color:rgba(247,239,230,.5)"><img src="${url(ICON)}" alt=""><span>Day So Far</span></div>` +
          `</div>`,
      }

    case 'glyph':
      return {
        field: FIELDS.warm,
        body:
          `<div class="pad c">` +
          `<h1 class="d" style="font-size:119px;line-height:1.02;color:${INK}">${p.head}<br>${p.tail}` +
          `<span class="glyph">${fig(p.name, p.mood, p.key)}</span></h1>` +
          `</div>` +
          mark('bottom:76px;left:97px', 'rgba(27,26,21,.5)'),
      }

    case 'pair':
      return {
        field: FIELDS.paper,
        body:
          // The foot clears the wordmark, which otherwise lands on a cell label.
          `<div class="pad col" style="padding:86px 86px 200px">` +
          `<h1 class="d" style="font-size:80px;line-height:1.04;color:${INK};max-width:15ch">${p.headline}</h1>` +
          `<div class="two">` +
          p.cells
            .map(
              (c, i) =>
                `<div class="cell">` +
                `<div class="h">${fig(c.name, c.mood, `${p.key}${i}`, c.prop)}</div>` +
                `<div class="t" style="font-size:44px;font-weight:700;color:${INK};line-height:1.15;margin-top:18px">${c.val}</div>` +
                `<div class="m500" style="font-size:26px;letter-spacing:.1em;text-transform:uppercase;color:#7d766c;margin-top:10px">${c.lbl}</div>` +
                `</div>`,
            )
            .join('') +
          `</div></div>` +
          mark('bottom:70px;left:86px', 'rgba(27,26,21,.4)'),
      }

    case 'carousel': {
      const size = figBox(0.448, 0.56)
      return {
        field: FIELDS.warm,
        body:
          `<div class="pad col" style="padding:86px">` +
          `<div class="m500" style="font-size:29px;letter-spacing:.14em;color:${JADE};text-transform:uppercase">${p.num}</div>` +
          `<h1 class="d" style="margin-top:43px;font-size:104px;line-height:1.01;color:${INK}">${p.headline}</h1>` +
          `</div>` +
          figure(p.name, p.mood, p.key, size, W - Math.round(size * 0.728), 0.215, false) +
          `<div class="swipe"><span class="dots"><b></b><b></b><b></b><b></b><b></b></span><span>Swipe</span></div>` +
          mark('top:86px;right:86px', 'rgba(27,26,21,.45)'),
      }
    }

    case 'crop': {
      // Far enough left that the held prop stays in frame. The headline names
      // it, and cropping the subject of the sentence out is the one crop this
      // layout cannot make.
      const size = figBox(0.768, 0.96)
      // A held prop reaches to about 0.93 of the box, so a figure placed for a
      // bare silhouette crops it off — at square worst of all, where the box
      // shrinks but the prop keeps its share of it. Give the prop the room and
      // let the crop happen on the figure's own edge instead.
      const bias = p.prop ? 0.945 : 0.852
      return {
        field: FIELDS.warm,
        body:
          figure(p.name, p.mood, p.key, size, W - Math.round(size * bias), 0.146, false, p.prop) +
          `<div class="tag" style="top:86px;left:86px;max-width:600px">` +
          `<h1 class="d" style="font-size:104px;line-height:1;color:${INK}">${p.headline}</h1></div>` +
          mark('bottom:76px;left:86px', 'rgba(27,26,21,.55)'),
      }
    }

    case 'split': {
      const half = Math.round(STAGE_H / 2)
      const size = figBox(0.448, 0.56)
      return {
        field: FIELDS.paper,
        body:
          `<div class="half-a" style="height:${half}px">` +
          `<h1 class="d" style="font-size:93px;line-height:1.02;color:${CREAM}">${p.headline}</h1></div>` +
          `<div class="half-b" style="top:${half}px;height:${STAGE_H - half}px">` +
          figure(p.name, p.mood, p.key, size, Math.round(W / 2 - size / 2), 0.142, false, p.prop) +
          `</div>` +
          // Left, not right: the figure is centred in the lower half and its
          // held prop reaches into the right corner.
          mark('bottom:65px;left:86px', 'rgba(27,26,21,.5)'),
      }
    }

    case 'staged': {
      const size = figBox(0.368, 0.46)
      return {
        field: FIELDS.night,
        body:
          `<span class="glow"></span>` +
          figure(p.name, p.mood, p.key, size, W - Math.round(size * 1.13), 0.131, true) +
          `<div class="tag" style="top:86px;left:86px;max-width:648px">` +
          `<h1 class="d" style="font-size:89px;line-height:1.02;color:${CREAM}">${p.headline}</h1>` +
          `<div class="t" style="font-weight:600;font-size:37px;line-height:1.4;color:rgba(247,239,230,.66);margin-top:43px;max-width:22ch">${p.sub}</div>` +
          `</div>` +
          mark('bottom:76px;left:86px', 'rgba(247,239,230,.55)'),
      }
    }
  }
}

/* ── page ───────────────────────────────────────────────────────────── */

const faces =
  `@font-face{font-family:'D';src:url('${url(FONTS.display)}') format('truetype');font-weight:800}` +
  `@font-face{font-family:'T';src:url('${url(FONTS.text400)}') format('woff2');font-weight:400}` +
  `@font-face{font-family:'T';src:url('${url(FONTS.text600)}') format('woff2');font-weight:600}` +
  `@font-face{font-family:'T';src:url('${url(FONTS.text700)}') format('woff2');font-weight:700}` +
  `@font-face{font-family:'M';src:url('${url(FONTS.mono400)}') format('woff2');font-weight:400}` +
  `@font-face{font-family:'M';src:url('${url(FONTS.mono500)}') format('woff2');font-weight:500}`

function page(p: Post, field: string, body: string): string {
  const ground = p.ground && existsSync(p.ground) ? `background-image:url('${url(p.ground)}');background-size:cover;background-position:center;` : ''
  return `<!doctype html>
<html><head><meta charset="utf-8"><style>
${faces}
*{margin:0;padding:0;box-sizing:border-box}
html,body{width:${W}px;height:${H}px;overflow:hidden}
body{position:relative;background:${field};${ground}-webkit-font-smoothing:antialiased}
/* The ground fills the frame; the composition lives in the stage. On story the
   two differ, which is what keeps every element out of Instagram's chrome. */
.stage{position:absolute;left:0;top:${STAGE_TOP}px;width:${W}px;height:${STAGE_H}px}
.d{font-family:'D',sans-serif;font-weight:800;letter-spacing:-.026em}
.t{font-family:'T',sans-serif}
.m400{font-family:'M',monospace;font-weight:400}
.m500{font-family:'M',monospace;font-weight:500}
.pad{position:absolute;inset:0;padding:97px;display:flex;flex-direction:column}
.pad.c{justify-content:center}
.pad.col{justify-content:flex-start}
.kicker{font-family:'T',sans-serif;font-weight:700;font-size:32px;letter-spacing:.1em;text-transform:uppercase;color:rgba(255,255,255,.78);margin-bottom:54px}
.list{list-style:none;display:flex;flex-direction:column;gap:33px}
.list li{display:flex;gap:32px;align-items:baseline}
.bars{display:flex;flex-direction:column;gap:37px}
.row{display:flex;align-items:center;gap:22px}
.bar{height:48px;border-radius:999px;flex:none}
.glyph{display:inline-block;width:119px;height:119px;vertical-align:-26px;margin-left:6px}
.glyph svg{width:100%;height:100%;overflow:visible}
.two{margin-top:auto;display:grid;grid-template-columns:1fr 1fr;gap:43px;align-items:end}
.cell{text-align:center}
.cell .h{height:${Math.round(STAGE_H * 0.244)}px}
.cell .h svg{width:100%;height:100%;overflow:visible}
.fig{position:absolute;display:block}
.fig svg{width:100%;height:100%;overflow:visible;display:block}
.halo,.shade{position:absolute;display:block}
.shade{border-radius:50%}
.tag{position:absolute}
.glow{position:absolute;inset:0;background:radial-gradient(58% 42% at 72% 76%,rgba(176,107,255,.34),transparent 70%)}
.half-a{position:absolute;top:0;left:0;width:${W}px;background:${INK};padding:86px;display:flex;align-items:flex-end}
.half-b{position:absolute;left:0;width:${W}px;background:linear-gradient(140deg,#dff0e6,#c9e6f5);overflow:hidden}
.swipe{position:absolute;bottom:76px;left:86px;display:flex;align-items:center;gap:26px;font-family:'M',monospace;font-weight:500;font-size:29px;letter-spacing:.1em;color:#7d766c;text-transform:uppercase}
.dots{display:flex;gap:15px}
.dots b{width:19px;height:19px;border-radius:50%;background:#cabfae;display:block}
.dots b:first-child{background:${JADE}}
.mark{position:absolute;display:flex;align-items:center;gap:24px;font-family:'T',sans-serif;font-weight:700}
.mark img{width:62px;height:62px;border-radius:16px;display:block;flex:none}
.mark span{font-size:28px;letter-spacing:.01em}
</style></head><body><div class="stage">${body}</div></body></html>`
}

/* ── run ────────────────────────────────────────────────────────────── */

const chosen = opts.only ? POSTS.filter((p) => p.key === opts.only || p.template === opts.only) : POSTS
if (!chosen.length) {
  console.error(`No post "${opts.only}". Keys: ${POSTS.map((p) => p.key).join(', ')}`)
  process.exit(1)
}

const CHROME = [
  'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
  'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
].find((p) => existsSync(p))
if (!CHROME) {
  console.error('No Chrome or Edge found to rasterise with.')
  process.exit(1)
}
for (const f of Object.values(FONTS)) {
  if (!existsSync(f)) {
    console.error(`Missing font: ${f}`)
    process.exit(1)
  }
}

mkdirSync(OUTDIR, { recursive: true })
let ok = 0
for (const p of chosen) {
  const { field, body } = render(p)
  const htmlPath = join(OUTDIR, `${p.key}-${SIZE}.html`)
  const pngPath = join(OUTDIR, `${p.key}-${SIZE}.png`)
  writeFileSync(htmlPath, page(p, field, body), 'utf8')

  const r = spawnSync(
    CHROME,
    [
      '--headless=new',
      '--disable-gpu',
      '--no-first-run',
      '--hide-scrollbars',
      '--force-device-scale-factor=1',
      `--window-size=${W},${H}`,
      `--screenshot=${resolve(pngPath)}`,
      url(htmlPath),
    ],
    { encoding: 'utf8' },
  )

  if (existsSync(pngPath)) {
    ok++
    console.log(`  ${p.key.padEnd(13)} ${p.template.padEnd(10)} ${(statSync(pngPath).size / 1024).toFixed(0).padStart(4)} KB`)
  } else {
    console.error(`  ${p.key.padEnd(13)} FAILED (status ${r.status})\n    ${(r.stderr ?? '').split('\n').slice(-4).join('\n    ')}`)
  }
}

console.log(`\n${ok}/${chosen.length} written to ${OUTDIR}/ at ${W}x${H}`)
process.exit(ok === chosen.length ? 0 : 1)
