#!/usr/bin/env tsx
// Nine post templates, and one post built from each.
//
//   npx tsx scripts/content/post.mts                  # all nine, 1080x1350
//   npx tsx scripts/content/post.mts --only statement
//   npx tsx scripts/content/post.mts --size story
//
// A template is a layout; a POSTS entry is the copy poured into one. To ship a
// new post, add an entry — the layouts are meant to be reused, not rewritten.
// The nine were picked off a layout board so they fail differently from each
// other: three carry no character at all, three keep it subordinate to type or
// data, three let it lead. A feed of nine variations on one shape reads as one
// post; this is the spread that stops it.
//
// Where each layer comes from:
//
//   cast   packages/shared/src/cast.ts — the same geometry the phone, the
//          widget and the site draw, at any size, in any of eighteen moods.
//          Never redrawn by hand, never regenerated by a model.
//   type   apps/mobile/assets/fonts — Baloo2 for the shouting, Nunito for
//          reading, IBM Plex Mono for timestamps and labels. All three SIL OFL.
//   ground a CSS field by default. Pass `ground` on an entry to lay a
//          ComfyUI render from content/gen/ underneath instead (§10) — texture
//          only, never a subject, and never anything a number could sit on.
//
// Composition rules the layouts encode, learned by getting them wrong first:
// a lineup is not a composition; a mood needs its scene (`stir` draws the ladle
// and not the pot); one face at one weight is the amateur tell; and a figure
// without a halo and a real contact shadow floats on the ground like a sticker.
//
// Rasterised by headless Chrome: the only renderer here that reads both SVG and
// a webfont (sharp is not installed, ffmpeg does neither).

import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { figureMarkup, GRID, type CastName, type Mood, type Prop } from '../../packages/shared/src/cast'

/* ── frame ──────────────────────────────────────────────────────────── */

const SIZES: Record<string, { w: number; h: number }> = {
  post: { w: 1080, h: 1350 },
  story: { w: 1080, h: 1920 },
  square: { w: 1080, h: 1080 },
}

const FLAGS = new Set(['size', 'out', 'only'])
const argv = process.argv.slice(2)
const opts: Record<string, string> = {}
for (let i = 0; i < argv.length; i++) {
  const a = argv[i]
  if (!a.startsWith('--')) continue
  const name = a.slice(2)
  if (!FLAGS.has(name)) {
    console.error(`Unknown flag --${name}. Known: ${[...FLAGS].join(', ')}`)
    process.exit(1)
  }
  opts[name] = argv[++i]
}

const SIZE = opts.size ?? 'post'
const OUTDIR = opts.out ?? 'content/out/posts'
if (!SIZES[SIZE]) {
  console.error(`Unknown --size ${SIZE}. Known: ${Object.keys(SIZES).join(', ')}`)
  process.exit(1)
}
const { w: W, h: H } = SIZES[SIZE]

/**
 * The composition is laid out in a stage, which is the frame everywhere except
 * story. A 9:16 story is mostly chrome — the top and bottom ~250px sit under
 * Instagram's own UI — so there the stage stays the 4:5 composition, centred,
 * while the ground fills the whole frame. That puts every element inside the
 * safe area by construction instead of by a table of insets, and it means one
 * set of coordinates renders all three sizes.
 */
const STAGE_H = SIZE === 'story' ? 1350 : H
const STAGE_TOP = Math.round((H - STAGE_H) / 2)

/**
 * A figure's box, as a share of the stage height but capped against the frame
 * width. Without the cap a tall frame grows the figure until it runs out of
 * the sides; without the height share a square frame keeps a figure sized for
 * a taller one and swallows the type.
 */
const figBox = (hFrac: number, wFrac: number) => Math.round(Math.min(STAGE_H * hFrac, W * wFrac))

const FONTS = {
  display: 'apps/mobile/assets/fonts/Baloo2_800ExtraBold.ttf',
  text400: 'apps/mobile/assets/fonts/Nunito_400.woff2',
  text600: 'apps/mobile/assets/fonts/Nunito_600.woff2',
  text700: 'apps/mobile/assets/fonts/Nunito_700.woff2',
  mono400: 'apps/mobile/assets/fonts/PlexMono_400.woff2',
  mono500: 'apps/mobile/assets/fonts/PlexMono_500.woff2',
}

// Sampled from store/feature-graphic.png, as scripts/content/cards.mjs does.
const INK = '#1b1a15'
const CREAM = '#f7efe6'
const JADE = '#0f9a5a'

/** Each figure's mid ramp stop, for the halo it stands in (cast.ts FIGURES). */
const HALO: Record<CastName, string> = { ember: '#ffa51f', skye: '#3b9eff', plum: '#b06bff' }

/* ── the posts ──────────────────────────────────────────────────────── */

interface Base {
  key: string
  /** Optional ComfyUI render from content/gen/ laid under the CSS field. */
  ground?: string
}
type Post = Base &
  (
    | { template: 'statement'; kicker: string; headline: string }
    | { template: 'typed-day'; day: string; entries: { t: string; m: string }[]; foot: string }
    | { template: 'macro-bar'; headline: string; rows: { k: string; p: number; c: number; f: number }[] }
    | { template: 'glyph'; head: string; tail: string; name: CastName; mood: Mood }
    | { template: 'pair'; headline: string; cells: { name: CastName; mood: Mood; prop?: Prop; val: string; lbl: string }[] }
    | { template: 'carousel'; num: string; headline: string; name: CastName; mood: Mood }
    | { template: 'crop'; headline: string; name: CastName; mood: Mood; prop?: Prop }
    | { template: 'split'; headline: string; name: CastName; mood: Mood; prop?: Prop }
    | { template: 'staged'; headline: string; sub: string; name: CastName; mood: Mood }
    // One slide of a slideshow. Never written by hand — SLIDESHOWS below is the
    // authoring surface, and every entry here is expanded from it.
    | { template: 'slide'; i: number; n: number; aside?: string; claim: string; reason?: string }
  )

// One post per template. Every line is an idea about eating that stands on its
// own: none names a feature, shows a screen, or puts a number on an image.
const POSTS: Post[] = [
  {
    key: '01-statement',
    template: 'statement',
    kicker: 'No app required',
    headline: 'Eat first.<br>Log after.',
  },
  {
    key: '02-typed-day',
    template: 'typed-day',
    day: 'Tuesday',
    entries: [
      { t: '08:10', m: 'Toast, two eggs, black coffee' },
      { t: '13:30', m: 'Leftover rice and whatever was in the fridge' },
      { t: '17:45', m: 'Most of a bar of dark chocolate, standing up' },
      { t: '21:20', m: 'Beer sausages and a lager' },
    ],
    foot: 'A day is four sentences.',
  },
  {
    key: '03-macro-bar',
    template: 'macro-bar',
    headline: 'Same calories. Different day.',
    // Widths in canvas px. Each row totals the same, which is the whole point.
    rows: [
      { k: 'Mon', p: 120, c: 360, f: 150 },
      { k: 'Tue', p: 330, c: 150, f: 150 },
    ],
  },
  {
    key: '04-glyph',
    template: 'glyph',
    head: 'Dinner was',
    tail: 'fine',
    name: 'plum',
    mood: 'idle',
  },
  {
    key: '05-pair',
    template: 'pair',
    headline: 'Two plates. One number. Nothing alike.',
    cells: [
      { name: 'ember', mood: 'proud', val: 'Chicken &amp; rice', lbl: 'protein led' },
      { name: 'plum', mood: 'hold', prop: 'mug', val: 'Pastry &amp; latte', lbl: 'fat led' },
    ],
  },
  {
    key: '06-carousel',
    template: 'carousel',
    num: '01 / 05',
    headline: 'Three things nobody says about logging food',
    name: 'skye',
    mood: 'thinking',
  },
  {
    key: '07-crop',
    template: 'crop',
    headline: 'Nobody weighs the toast',
    name: 'ember',
    mood: 'hold',
    prop: 'toast',
  },
  {
    key: '08-split',
    template: 'split',
    headline: 'You already know what went in the bowl',
    name: 'skye',
    mood: 'hold',
    prop: 'bowl',
  },
  {
    key: '09-staged',
    template: 'staged',
    headline: 'A 1am snack belongs to yesterday',
    sub: 'Your day ends when you sleep, not at midnight.',
    name: 'plum',
    mood: 'sleepy',
    ground: 'content/gen/dsf3_grad_night_00001_.png',
  },
]

/* ── slideshows ─────────────────────────────────────────────────────── */

/**
 * The nine templates above each make one post. A slideshow is the other shape:
 * one idea split across four or five slides that are read by swiping, and the
 * format that carries furthest right now on both TikTok and Reels.
 *
 * Three beats per slide, in this order, because that is the arrangement the
 * high-performing ones use and it is doing real work:
 *
 *   aside    a parenthetical, small. Reassurance or an aside — it lowers the
 *            stakes before the claim lands.
 *   claim    numbered, largest, the thing being said. On slide 0 this is the
 *            hook and there is nothing else.
 *   reason   one sentence on why it is true. Not a second claim.
 *
 * Set in white pills on a photograph rather than white type over it: it is what
 * a native caption looks like on both platforms, and it survives a bright
 * ground, which white type does not. `box-decoration-break:clone` is what gives
 * every wrapped line its own pill instead of one box behind the block.
 *
 * The grounds come from content/stock/ — real photographs, pulled by
 * scripts/content/stock.mts. Per §0 nothing here may put a number on one, which
 * is why a slide's beats carry sentences and never a figure.
 */
interface Slideshow {
  key: string
  /** A set under content/stock/ whose photographs ground the slides. */
  stock: string
  /** Slide 0, alone on the cover. Taken from content/hooks/hooks.txt. */
  hook: string
  beats: { aside?: string; claim: string; reason?: string }[]
  /**
   * Explicit grounds, one per slide including the cover, when the photograph is
   * part of the point rather than a backdrop. The library formats generated by
   * `slides.mts` set this: a guess-the-calories slide has to show *that* dish,
   * and a random photograph of somebody else's lunch would make the number a
   * lie. Falls back to the `stock` set when absent.
   */
  grounds?: (string | undefined)[]
}

// The hook is "The 3 ways to log a meal here, in order of laziness:" — so the
// beats run laziest first, and every one is a thing the composer actually does:
// the mic icon, the camera icon, and the app's own "No forms, nothing to
// search for."
const SLIDESHOWS: Slideshow[] = [
  {
    key: '10-three-ways',
    stock: 'meals',
    hook: 'The 3 ways to log a meal here,<br>in order of laziness:',
    beats: [
      {
        aside: '(the one you will actually use)',
        claim: '1. Say it out loud',
        reason: 'Hold the mic and talk. Toast, two eggs, black coffee. Nothing to search for.',
      },
      {
        aside: '(for the meals you did not cook)',
        claim: '2. Photograph it',
        reason: 'Point the camera at the plate and let the composer take it from there.',
      },
      {
        aside: '(when you already know what it was)',
        claim: '3. Type one sentence',
        reason: 'Plain language, the way you would tell a friend. Not a form.',
      },
    ],
  },

  // "4 numbers I track besides calories:" — the Diet Quality card, which is the
  // one screen in the tour that no other tracker's free tier shows. Four beats
  // because the card holds exactly four, and the hook promises four.
  {
    key: '11-four-numbers',
    stock: 'meals',
    hook: '4 numbers I track<br>besides calories:',
    beats: [
      {
        aside: '(the one that actually changed what I cook)',
        claim: '1. Fibre',
        reason: 'Nothing else predicts whether a day left me full. Calories certainly do not.',
      },
      {
        aside: '(the one restaurants decide for you)',
        claim: '2. Sodium',
        reason: 'You can eat a light lunch and still take most of a day of salt with it.',
      },
      {
        aside: '(the two that hide in the same foods)',
        claim: '3 & 4. Saturated fat and sugar',
        reason: 'Same total, different afternoon. A number on its own does not tell you which.',
      },
    ],
  },

  // Build-in-public. §5 ranks this second and it costs nothing to make, because
  // it is true and needs no footage the app cannot produce.
  {
    key: '12-six-months',
    stock: 'evening',
    hook: 'Six months of evenings.<br>Here is what shipped:',
    beats: [
      {
        aside: '(the entire premise)',
        claim: 'Say what you ate',
        reason: 'One sentence, out loud or typed. The parsing is the product; the form was the problem.',
      },
      {
        aside: '(what I could not find anywhere else)',
        claim: 'Fibre, sodium, sugar, sat fat',
        reason: 'Every tracker counts calories. Almost none of them show you the rest for free.',
      },
      {
        aside: '(the part nobody asks for until month two)',
        claim: 'A month you can look back at',
        reason: 'A calendar of real days beats a streak counter that punishes you for one gap.',
      },
    ],
  },

  // Pure relatability, no feature claim at all. The one post here that is about
  // the viewer rather than the app, which is why it can afford to be first.
  {
    key: '13-nine-pm',
    stock: 'counter',
    hook: 'Tell me you have never rebuilt<br>lunch from memory at 9pm',
    beats: [
      {
        aside: '(be honest)',
        claim: 'You had the bowl in your hands',
        reason: 'You knew exactly what was in it. Eight hours ago.',
      },
      {
        aside: '(this is the actual reason people quit)',
        claim: 'It was never the knowing',
        reason: 'It was that saying so took ninety seconds and eleven taps, three times a day.',
      },
      {
        aside: '(so log it at the table)',
        claim: 'Before you put the fork down',
        reason: 'One sentence while the details are still in front of you. Then forget about it.',
      },
    ],
  },

  // The tour, as a tour. "4 screens" is exactly what app-tour.mp4 walks through,
  // in order, which is what makes the count payable.
  {
    key: '14-four-screens',
    stock: 'market',
    hook: '4 screens.<br>That is the whole app:',
    beats: [
      {
        aside: '(where you spend nine seconds a day)',
        claim: '1. Journal',
        reason: 'One question — what have you eaten today — and three ways to answer it.',
      },
      {
        aside: '(where you look when you are deciding dinner)',
        claim: '2. Today',
        reason: 'The ring, the three macros, and the four numbers underneath them.',
      },
      {
        aside: '(the two nobody demos, and the reason people stay)',
        claim: '3 & 4. Progress and History',
        reason: 'A weight trend that is not a verdict, and a month of real days you can scroll back through.',
      },
    ],
  },
]

/**
 * Photographs for a slideshow's grounds, one per slide, by sorted filename so a
 * given slideshow keeps the same grounds between runs. Pexels ids are not
 * stable across re-pulls, so these are never named in a SLIDESHOWS entry —
 * naming one would break the moment stock.mts ran again.
 *
 * An empty or absent set is not an error: page() falls back to the CSS field,
 * which is a plain poster and still a legible slide.
 */
function stockGrounds(set: string, want: number, seed = ''): (string | undefined)[] {
  const dir = join('content/stock', set)
  const files = existsSync(dir)
    ? readdirSync(dir)
        .filter((f) => f.endsWith('.jpg') && !f.startsWith('_'))
        .sort()
    : []
  if (!files.length) return Array.from({ length: want }, () => undefined)

  /*
   * Offset by the slideshow's own key, or every slideshow sharing a set opens
   * on the same photograph. Two of these went out with the identical pasta bowl
   * on both covers and three more repeats between them, which in a feed reads
   * as one post published twice — the §488 tell, arrived at from the other
   * direction.
   *
   * A sum of char codes and not a real hash: it has to be stable between runs
   * so a re-render keeps a slideshow's grounds, and it has to spread eight
   * files across five slideshows. That is all.
   */
  let offset = 0
  for (const ch of seed) offset = (offset + ch.charCodeAt(0)) % files.length
  return Array.from({ length: want }, (_, i) => join(dir, files[(offset + i) % files.length]))
}

function expand(s: Slideshow): Post[] {
  const n = s.beats.length + 1
  const grounds = s.grounds ?? stockGrounds(s.stock, n, s.key)
  return [
    { key: `${s.key}-0`, template: 'slide', i: 0, n, claim: s.hook, ground: grounds[0] },
    ...s.beats.map(
      (b, j): Post => ({
        key: `${s.key}-${j + 1}`,
        template: 'slide',
        i: j + 1,
        n,
        aside: b.aside,
        claim: b.claim,
        reason: b.reason,
        ground: grounds[j + 1],
      }),
    ),
  ]
}

/**
 * Slideshows written by the model, from `scripts/content/suggest.mts`.
 *
 * Kept as files rather than appended to SLIDESHOWS above so the two stay
 * distinguishable: the array is authored and reviewed in code review, these
 * arrive from a batch and are judged in the panel. A generated slideshow that
 * turns out to be good can be promoted by hand into the array; one that is bad
 * is a deleted file.
 *
 * Validated loosely here — the real validation is `SuggestedSlideshow` in
 * `ai/slides.ts`, which ran before the file was written. This only checks the
 * shape it needs, so a hand-edited file fails with the filename rather than a
 * stack trace three functions deeper.
 */
function loadGenerated(): Slideshow[] {
  const dir = 'content/slides'
  if (!existsSync(dir)) return []
  const shows: Slideshow[] = []
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.json')).sort()) {
    const raw = JSON.parse(readFileSync(join(dir, file), 'utf8')) as Slideshow
    if (!raw.key || !raw.hook || !Array.isArray(raw.beats) || !raw.beats.length) {
      console.error(`${join(dir, file)}: needs key, hook and a non-empty beats array`)
      process.exit(1)
    }
    shows.push({ stock: 'meals', ...raw })
  }
  return shows
}

const SLIDES: Post[] = [...SLIDESHOWS, ...loadGenerated()].flatMap(expand)

/* ── helpers ────────────────────────────────────────────────────────── */

const url = (p: string) => pathToFileURL(resolve(p)).href

/** One figure as a standalone SVG. `prefix` keeps gradient ids apart. */
function fig(name: CastName, mood: Mood, prefix: string, prop?: Prop): string {
  const f = figureMarkup(name, mood, prefix, prop)
  return `<svg viewBox="0 0 ${GRID} ${GRID}" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs>${f.defs}</defs>${f.shapes}</svg>`
}

/**
 * The signature: the real app icon, never the product name typed out and never
 * a coloured square standing in for it. store/icon-512.png is the jade ring
 * with the three macro dots inside — the drawing the cast came out of
 * (CAST.md), so the mark and the characters are visibly one family. Its ground
 * is cream rather than transparent, so it is set as a rounded tile and reads as
 * the app icon on a light field or a dark one.
 */
const ICON = 'store/icon-512.png'
function mark(pos: string, colour: string): string {
  return `<div class="mark" style="${pos};color:${colour}"><img src="${url(ICON)}" alt=""><span>Day So Far</span></div>`
}

/**
 * A halo in the figure's own colour and a blurred contact shadow, so it stands
 * on the ground instead of floating above it. `size` is the figure's box.
 */
function grounding(name: CastName, left: number, bottom: number, size: number, dark: boolean): string {
  const halo = `left:${Math.round(left - size * 0.14)}px;bottom:${Math.round(bottom - size * 0.1)}px;width:${Math.round(size * 1.28)}px;height:${Math.round(size * 1.28)}px;background:radial-gradient(circle at 50% 50%,${HALO[name]}${dark ? '3d' : '2b'} 0%,transparent 62%)`
  const shade = `left:${Math.round(left + size * 0.19)}px;bottom:${Math.round(bottom + size * 0.055)}px;width:${Math.round(size * 0.62)}px;height:${Math.round(size * 0.1)}px;background:${dark ? 'rgba(0,0,0,.42)' : 'rgba(27,26,21,.16)'};filter:blur(${Math.round(size * 0.035)}px)`
  return `<span class="halo" style="${halo}"></span><span class="shade" style="${shade}"></span>`
}

/** A grounded figure: its halo, its contact shadow and the drawing, placed. */
function figure(
  name: CastName,
  mood: Mood,
  prefix: string,
  size: number,
  left: number,
  /** How far past the stage's foot it sinks, as a share of its own box. */
  sink: number,
  dark: boolean,
  prop?: Prop,
): string {
  const bottom = Math.round(-size * sink)
  return (
    grounding(name, left, bottom, size, dark) +
    `<span class="fig" style="left:${left}px;bottom:${bottom}px;width:${size}px;height:${size}px">${fig(name, mood, prefix, prop)}</span>`
  )
}

const FIELDS: Record<string, string> = {
  warm: 'linear-gradient(152deg,#f7e0bd 0%,#efe6d2 38%,#dfeadb 72%,#cfe7d8 100%)',
  night: 'linear-gradient(158deg,#221d3a 0%,#2c2a4d 45%,#3b3a5e 100%)',
  amber: 'linear-gradient(150deg,#ffc266 0%,#f09733 100%)',
  ink: '#1b1a15',
  paper: '#fdf8f0',
}

/* ── templates ──────────────────────────────────────────────────────── */

/** Each returns the field it sits on and the markup that goes over it. */
function render(p: Post): { field: string; body: string } {
  switch (p.template) {
    case 'statement':
      return {
        field: FIELDS.amber,
        body:
          `<div class="pad c">` +
          `<div class="kicker">${p.kicker}</div>` +
          `<h1 class="d" style="font-size:130px;line-height:.96;color:#fffdf9">${p.headline}</h1>` +
          `</div>` +
          mark('bottom:76px;left:97px', 'rgba(255,255,255,.78)'),
      }

    case 'typed-day':
      return {
        field: FIELDS.paper,
        body:
          `<div class="pad col">` +
          `<div class="m500" style="font-size:29px;letter-spacing:.12em;text-transform:uppercase;color:#a89f92;margin-bottom:54px">${p.day}</div>` +
          `<ul class="list">` +
          p.entries
            .map(
              (e) =>
                `<li><span class="m400" style="font-size:31px;color:#b3a998;flex:none;width:119px">${e.t}</span>` +
                `<span class="t" style="font-size:44px;font-weight:600;color:${INK};line-height:1.25">${e.m}</span></li>`,
            )
            .join('') +
          `</ul>` +
          `<div class="t" style="margin-top:auto;font-size:38px;font-weight:700;color:${JADE}">${p.foot}</div>` +
          `</div>` +
          mark('bottom:76px;right:97px', 'rgba(27,26,21,.45)'),
      }

    case 'macro-bar':
      return {
        field: FIELDS.ink,
        body:
          `<div class="pad col" style="justify-content:space-between;padding:86px">` +
          `<h1 class="d" style="font-size:89px;line-height:1.02;color:${CREAM};max-width:13ch">${p.headline}</h1>` +
          `<div class="bars">` +
          p.rows
            .map(
              (r) =>
                `<div class="row">` +
                `<span class="m500" style="font-size:28px;letter-spacing:.1em;text-transform:uppercase;color:rgba(247,239,230,.55);width:110px;flex:none">${r.k}</span>` +
                `<span class="bar" style="background:#ffa51f;width:${r.p}px"></span>` +
                `<span class="bar" style="background:#3b9eff;width:${r.c}px"></span>` +
                `<span class="bar" style="background:#b06bff;width:${r.f}px"></span>` +
                `</div>`,
            )
            .join('') +
          `</div>` +
          `<div class="mark" style="position:static;color:rgba(247,239,230,.5)"><img src="${url(ICON)}" alt=""><span>Day So Far</span></div>` +
          `</div>`,
      }

    case 'glyph':
      return {
        field: FIELDS.warm,
        body:
          `<div class="pad c">` +
          `<h1 class="d" style="font-size:119px;line-height:1.02;color:${INK}">${p.head}<br>${p.tail}` +
          `<span class="glyph">${fig(p.name, p.mood, p.key)}</span></h1>` +
          `</div>` +
          mark('bottom:76px;left:97px', 'rgba(27,26,21,.5)'),
      }

    case 'pair':
      return {
        field: FIELDS.paper,
        body:
          // The foot clears the wordmark, which otherwise lands on a cell label.
          `<div class="pad col" style="padding:86px 86px 200px">` +
          `<h1 class="d" style="font-size:80px;line-height:1.04;color:${INK};max-width:15ch">${p.headline}</h1>` +
          `<div class="two">` +
          p.cells
            .map(
              (c, i) =>
                `<div class="cell">` +
                `<div class="h">${fig(c.name, c.mood, `${p.key}${i}`, c.prop)}</div>` +
                `<div class="t" style="font-size:44px;font-weight:700;color:${INK};line-height:1.15;margin-top:18px">${c.val}</div>` +
                `<div class="m500" style="font-size:26px;letter-spacing:.1em;text-transform:uppercase;color:#7d766c;margin-top:10px">${c.lbl}</div>` +
                `</div>`,
            )
            .join('') +
          `</div></div>` +
          mark('bottom:70px;left:86px', 'rgba(27,26,21,.4)'),
      }

    case 'slide': {
      // The cover carries the hook and nothing else, so it gets the larger type
      // and sits centred. A beat slide stacks its three parts and sits slightly
      // above centre, where the caption lands on both platforms and clears the
      // Reels action rail on the right.
      const cover = p.i === 0
      const beats = [
        p.aside ? `<p class="beat"><span class="cap aside">${p.aside}</span></p>` : '',
        `<p class="beat"><span class="cap claim${cover ? ' cover' : ''}">${p.claim}</span></p>`,
        p.reason ? `<p class="beat"><span class="cap reason">${p.reason}</span></p>` : '',
      ]
        .filter(Boolean)
        .join('')
      const pips = Array.from(
        { length: p.n },
        (_, k) => `<b class="${k === p.i ? 'on' : ''}"></b>`,
      ).join('')
      return {
        field: FIELDS.warm,
        body:
          `<div class="slide${cover ? ' mid' : ''}">${beats}</div>` +
          `<div class="pips">${pips}</div>` +
          mark('top:76px;left:86px', 'rgba(255,255,255,.96)'),
      }
    }

    case 'carousel': {
      const size = figBox(0.448, 0.56)
      return {
        field: FIELDS.warm,
        body:
          `<div class="pad col" style="padding:86px">` +
          `<div class="m500" style="font-size:29px;letter-spacing:.14em;color:${JADE};text-transform:uppercase">${p.num}</div>` +
          `<h1 class="d" style="margin-top:43px;font-size:104px;line-height:1.01;color:${INK}">${p.headline}</h1>` +
          `</div>` +
          figure(p.name, p.mood, p.key, size, W - Math.round(size * 0.728), 0.215, false) +
          `<div class="swipe"><span class="dots"><b></b><b></b><b></b><b></b><b></b></span><span>Swipe</span></div>` +
          mark('top:86px;right:86px', 'rgba(27,26,21,.45)'),
      }
    }

    case 'crop': {
      // Far enough left that the held prop stays in frame. The headline names
      // it, and cropping the subject of the sentence out is the one crop this
      // layout cannot make.
      const size = figBox(0.768, 0.96)
      // A held prop reaches to about 0.93 of the box, so a figure placed for a
      // bare silhouette crops it off — at square worst of all, where the box
      // shrinks but the prop keeps its share of it. Give the prop the room and
      // let the crop happen on the figure's own edge instead.
      const bias = p.prop ? 0.945 : 0.852
      return {
        field: FIELDS.warm,
        body:
          figure(p.name, p.mood, p.key, size, W - Math.round(size * bias), 0.146, false, p.prop) +
          `<div class="tag" style="top:86px;left:86px;max-width:600px">` +
          `<h1 class="d" style="font-size:104px;line-height:1;color:${INK}">${p.headline}</h1></div>` +
          mark('bottom:76px;left:86px', 'rgba(27,26,21,.55)'),
      }
    }

    case 'split': {
      const half = Math.round(STAGE_H / 2)
      const size = figBox(0.448, 0.56)
      return {
        field: FIELDS.paper,
        body:
          `<div class="half-a" style="height:${half}px">` +
          `<h1 class="d" style="font-size:93px;line-height:1.02;color:${CREAM}">${p.headline}</h1></div>` +
          `<div class="half-b" style="top:${half}px;height:${STAGE_H - half}px">` +
          figure(p.name, p.mood, p.key, size, Math.round(W / 2 - size / 2), 0.142, false, p.prop) +
          `</div>` +
          // Left, not right: the figure is centred in the lower half and its
          // held prop reaches into the right corner.
          mark('bottom:65px;left:86px', 'rgba(27,26,21,.5)'),
      }
    }

    case 'staged': {
      const size = figBox(0.368, 0.46)
      return {
        field: FIELDS.night,
        body:
          `<span class="glow"></span>` +
          figure(p.name, p.mood, p.key, size, W - Math.round(size * 1.13), 0.131, true) +
          `<div class="tag" style="top:86px;left:86px;max-width:648px">` +
          `<h1 class="d" style="font-size:89px;line-height:1.02;color:${CREAM}">${p.headline}</h1>` +
          `<div class="t" style="font-weight:600;font-size:37px;line-height:1.4;color:rgba(247,239,230,.66);margin-top:43px;max-width:22ch">${p.sub}</div>` +
          `</div>` +
          mark('bottom:76px;left:86px', 'rgba(247,239,230,.55)'),
      }
    }
  }
}

/* ── page ───────────────────────────────────────────────────────────── */

const faces =
  `@font-face{font-family:'D';src:url('${url(FONTS.display)}') format('truetype');font-weight:800}` +
  `@font-face{font-family:'T';src:url('${url(FONTS.text400)}') format('woff2');font-weight:400}` +
  `@font-face{font-family:'T';src:url('${url(FONTS.text600)}') format('woff2');font-weight:600}` +
  `@font-face{font-family:'T';src:url('${url(FONTS.text700)}') format('woff2');font-weight:700}` +
  `@font-face{font-family:'M';src:url('${url(FONTS.mono400)}') format('woff2');font-weight:400}` +
  `@font-face{font-family:'M';src:url('${url(FONTS.mono500)}') format('woff2');font-weight:500}`

function page(p: Post, field: string, body: string): string {
  const ground = p.ground && existsSync(p.ground) ? `background-image:url('${url(p.ground)}');background-size:cover;background-position:center;` : ''
  return `<!doctype html>
<html><head><meta charset="utf-8"><style>
${faces}
*{margin:0;padding:0;box-sizing:border-box}
html,body{width:${W}px;height:${H}px;overflow:hidden}
body{position:relative;background:${field};${ground}-webkit-font-smoothing:antialiased}
/* The ground fills the frame; the composition lives in the stage. On story the
   two differ, which is what keeps every element out of Instagram's chrome. */
.stage{position:absolute;left:0;top:${STAGE_TOP}px;width:${W}px;height:${STAGE_H}px}
.d{font-family:'D',sans-serif;font-weight:800;letter-spacing:-.026em}
.t{font-family:'T',sans-serif}
.m400{font-family:'M',monospace;font-weight:400}
.m500{font-family:'M',monospace;font-weight:500}
.pad{position:absolute;inset:0;padding:97px;display:flex;flex-direction:column}
.pad.c{justify-content:center}
.pad.col{justify-content:flex-start}
.kicker{font-family:'T',sans-serif;font-weight:700;font-size:32px;letter-spacing:.1em;text-transform:uppercase;color:rgba(255,255,255,.78);margin-bottom:54px}
.list{list-style:none;display:flex;flex-direction:column;gap:33px}
.list li{display:flex;gap:32px;align-items:baseline}
.bars{display:flex;flex-direction:column;gap:37px}
.row{display:flex;align-items:center;gap:22px}
.bar{height:48px;border-radius:999px;flex:none}
.glyph{display:inline-block;width:119px;height:119px;vertical-align:-26px;margin-left:6px}
.glyph svg{width:100%;height:100%;overflow:visible}
.two{margin-top:auto;display:grid;grid-template-columns:1fr 1fr;gap:43px;align-items:end}
.cell{text-align:center}
.cell .h{height:${Math.round(STAGE_H * 0.244)}px}
.cell .h svg{width:100%;height:100%;overflow:visible}
.fig{position:absolute;display:block}
.fig svg{width:100%;height:100%;overflow:visible;display:block}
.halo,.shade{position:absolute;display:block}
.shade{border-radius:50%}
.tag{position:absolute}
.glow{position:absolute;inset:0;background:radial-gradient(58% 42% at 72% 76%,rgba(176,107,255,.34),transparent 70%)}
.half-a{position:absolute;top:0;left:0;width:${W}px;background:${INK};padding:86px;display:flex;align-items:flex-end}
.half-b{position:absolute;left:0;width:${W}px;background:linear-gradient(140deg,#dff0e6,#c9e6f5);overflow:hidden}
.swipe{position:absolute;bottom:76px;left:86px;display:flex;align-items:center;gap:26px;font-family:'M',monospace;font-weight:500;font-size:29px;letter-spacing:.1em;color:#7d766c;text-transform:uppercase}
.dots{display:flex;gap:15px}
.dots b{width:19px;height:19px;border-radius:50%;background:#cabfae;display:block}
.dots b:first-child{background:${JADE}}
/* Slideshow. The beats sit above centre on a beat slide and dead centre on the
   cover; .cap is inline so box-decoration-break gives each wrapped line its own
   pill, which is what a native caption looks like. line-height carries the
   pill's height, so it cannot drop below ~1.45 without the rows touching. */
.slide{position:absolute;inset:0;padding:120px 92px;display:flex;flex-direction:column;justify-content:flex-start;align-items:center;gap:26px;text-align:center;padding-top:${Math.round(STAGE_H * 0.16)}px}
.slide.mid{justify-content:center;padding-top:120px}
.beat{width:100%}
.cap{display:inline;background:#fff;color:${INK};box-decoration-break:clone;-webkit-box-decoration-break:clone;padding:.1em .26em;border-radius:12px}
.cap.aside{font-family:'T',sans-serif;font-weight:600;font-size:40px;line-height:1.66}
.cap.claim{font-family:'D',sans-serif;font-weight:800;letter-spacing:-.022em;font-size:78px;line-height:1.5}
.cap.claim.cover{font-size:94px;line-height:1.46}
.cap.reason{font-family:'T',sans-serif;font-weight:600;font-size:43px;line-height:1.62}
.pips{position:absolute;bottom:78px;left:0;width:${W}px;display:flex;justify-content:center;gap:16px}
.pips b{width:19px;height:19px;border-radius:50%;background:rgba(255,255,255,.55);display:block;box-shadow:0 1px 3px rgba(0,0,0,.28)}
.pips b.on{background:#fff}
.mark{position:absolute;display:flex;align-items:center;gap:24px;font-family:'T',sans-serif;font-weight:700}
.mark img{width:62px;height:62px;border-radius:16px;display:block;flex:none}
.mark span{font-size:28px;letter-spacing:.01em}
</style></head><body><div class="stage">${body}</div></body></html>`
}

/* ── run ────────────────────────────────────────────────────────────── */

// The nine posts and every slide of every slideshow render through one loop:
// --only takes a key, a template, or a slideshow's key to get its slides.
const ALL: Post[] = [...POSTS, ...SLIDES]
const chosen = opts.only
  ? ALL.filter((p) => p.key === opts.only || p.template === opts.only || p.key.startsWith(`${opts.only}-`))
  : ALL
if (!chosen.length) {
  console.error(`No post "${opts.only}". Keys: ${ALL.map((p) => p.key).join(', ')}`)
  process.exit(1)
}

// Windows first because that is where the 4080 and the render work live, but
// the poster builder needs no GPU and §1 puts the assembly line on the Mac —
// where this would exit "no Chrome found" with a browser plainly installed.
const CHROME = [
  'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
  'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
  '/Applications/Chromium.app/Contents/MacOS/Chromium',
  '/usr/bin/google-chrome',
  '/usr/bin/chromium',
].find((p) => existsSync(p))
if (!CHROME) {
  console.error('No Chrome or Edge found to rasterise with.')
  process.exit(1)
}
for (const f of Object.values(FONTS)) {
  if (!existsSync(f)) {
    console.error(`Missing font: ${f}`)
    process.exit(1)
  }
}

mkdirSync(OUTDIR, { recursive: true })
let ok = 0
for (const p of chosen) {
  const { field, body } = render(p)
  const htmlPath = join(OUTDIR, `${p.key}-${SIZE}.html`)
  const pngPath = join(OUTDIR, `${p.key}-${SIZE}.png`)
  writeFileSync(htmlPath, page(p, field, body), 'utf8')

  const r = spawnSync(
    CHROME,
    [
      '--headless=new',
      '--disable-gpu',
      '--no-first-run',
      '--hide-scrollbars',
      '--force-device-scale-factor=1',
      `--window-size=${W},${H}`,
      `--screenshot=${resolve(pngPath)}`,
      url(htmlPath),
    ],
    { encoding: 'utf8' },
  )

  if (existsSync(pngPath)) {
    ok++
    console.log(`  ${p.key.padEnd(13)} ${p.template.padEnd(10)} ${(statSync(pngPath).size / 1024).toFixed(0).padStart(4)} KB`)
  } else {
    console.error(`  ${p.key.padEnd(13)} FAILED (status ${r.status})\n    ${(r.stderr ?? '').split('\n').slice(-4).join('\n    ')}`)
  }
}

console.log(`\n${ok}/${chosen.length} written to ${OUTDIR}/ at ${W}x${H}`)
process.exit(ok === chosen.length ? 0 : 1)
